name: Validate_HACS

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4.2.2'
      - name: HACS validation
        uses: 'hacs/action@main'
        with:
          category: 'integration'