name: Validate_HACS

on:
  push:

jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4.2.2'
      - name: HACS validation
        uses: 'hacs/action@main'
        with:
          category: 'integration'